return {
    {
        "wounds",
        "health",
        "toughness",
        "tough_regen_delay",
        "tough_regen_still",
        "tough_regen_moving",
        "tough_bounty",
        "total_score",
    },
    {
        "stamina",
        "stamina_regen",
        "sprint_speed",
        "sprint_time",
        "dodge_count",
        "dodge_dist",
        "crit_chance",
        "crit_dmg",
    },
}